######################################################################
# Automatically generated by qmake (3.1) Thu Oct 2 14:50:41 2025
######################################################################

TEMPLATE = app
TARGET = "Senior Project main"
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += DbcParser.h DbcSender.h
SOURCES += DbcParser.cpp \
           DbcSender.cpp \
           main.cpp \
           test_connection.cpp \
           test_server.cpp \
           build_new/appdbc_parser_qmltyperegistrations.cpp \
           build_test/appdbc_parser_qmltyperegistrations.cpp \
           DBCClient/client.cpp \
           build_new/appDBC_Parser_autogen/mocs_compilation.cpp \
           build_test/appDBC_Parser_autogen/mocs_compilation.cpp \
           build/CMakeFiles/3.24.4/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build_new/CMakeFiles/3.24.4/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build_test/CMakeFiles/3.24.4/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += build_new/DBC_Parser/appDBC_Parser_qml_module_dir_map.qrc \
             build_test/DBC_Parser/appDBC_Parser_qml_module_dir_map.qrc \
             resources.qrc
TRANSLATIONS += build_new/CMakeFiles/all_aotstats.dir/compiler_depend.ts \
                build_new/CMakeFiles/all_qmllint.dir/compiler_depend.ts \
                build_new/CMakeFiles/all_qmllint_json.dir/compiler_depend.ts \
                build_new/CMakeFiles/all_qmllint_module.dir/compiler_depend.ts \
                build_new/CMakeFiles/all_qmltyperegistrations.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_autogen.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_automoc_json_extraction.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_copy_qml.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_copy_res.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_qmlimportscan.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_qmllint.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_qmllint_json.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_qmllint_module.dir/compiler_depend.ts \
                build_new/CMakeFiles/appDBC_Parser_qmltyperegistration.dir/compiler_depend.ts \
                build_new/CMakeFiles/module_appDBC_Parser_aotstats_target.dir/compiler_depend.ts \
                build_test/CMakeFiles/all_aotstats.dir/compiler_depend.ts \
                build_test/CMakeFiles/all_qmllint.dir/compiler_depend.ts \
                build_test/CMakeFiles/all_qmllint_json.dir/compiler_depend.ts \
                build_test/CMakeFiles/all_qmllint_module.dir/compiler_depend.ts \
                build_test/CMakeFiles/all_qmltyperegistrations.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_autogen.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_automoc_json_extraction.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_copy_qml.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_copy_res.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_qmlimportscan.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_qmllint.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_qmllint_json.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_qmllint_module.dir/compiler_depend.ts \
                build_test/CMakeFiles/appDBC_Parser_qmltyperegistration.dir/compiler_depend.ts \
                build_test/CMakeFiles/module_appDBC_Parser_aotstats_target.dir/compiler_depend.ts

# Windows-specific settings
win32 {
  RC_FILE = appicon.rc
}
